//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Be
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily
    {
        public int id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string date { get; set; }
        public Nullable<int> cost { get; set; }
        public string timeIn { get; set; }
        public string timeOut { get; set; }
    }
}
